### ISSUE TITLE
Error 403  Requests from referer empty are blocked

### ISSUE THREAD

**Issue by drjoju** [tanmuhittin/laravel-google-translate#18]
Hello,

I am getting a 403 error when I use the Google API. This happens when we restrict requests for use of the key to the specified websites in the Google console.

The error is something like
```
{
  "error": {
    "code": 403,
    "message": "Requests from referer \u003cempty\u003e are blocked.",
    "errors": [
      {
        "message": "Requests from referer \u003cempty\u003e are blocked.",
        "domain": "usageLimits",
        "reason": "rateLimitExceeded"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```
The problem is located in TranslateFilesCommand.php in the translate_via_api_key function.

The solution is to add the following line

        curl_setopt($handle, CURLOPT_REFERER, $refererUrl);

where refererUrl is the referer url site. This variable can be passed by value in the function or or obtained globally.

I'm doing something wrong or my proposal is correct?

Thanks in advance

**Comment by tanmuhittin** [comment]
Sorry for the late reply. Your proposal is correct, for using API keys this option can be added in the config file.

**Comment by tanmuhittin** [comment]
This package now using google/cloud-translate for requests
