### ISSUE TITLE
resulted in a `429 Too Many Requests` response

### ISSUE THREAD

**Issue by ahkmunna** [tanmuhittin/laravel-google-translate#19]
Got this error:
resulted in a `429 Too Many Requests` response

**Comment by ahkmunna** [comment]
Found the reason

**Comment by briavers** [comment]
@ahkmunna can you remember what is was?

**Comment by ahkmunna** [comment]
> @ahkmunna can you remember what is was?

I've fixed the issue and it merged to the main package. So the issue should solve now.
