### ISSUE TITLE
Problem compatibility Laravel 7

### ISSUE THREAD

**Issue by NicolasKulka** [tanmuhittin/laravel-google-translate#30]
When do you plan to go to Laravel 7?

**Comment by robsonrk** [comment]
master branch already on Laravel 7.

add this line to your composer.json require section
` "tanmuhittin/laravel-google-translate": "dev-master as 1.0.3"`

**Comment by NicolasKulka** [comment]
Thanks, because dependance in "barryvdh/laravel-translation-manager"

**Comment by robsonrk** [comment]
same for me

**Comment by LazyTechwork** [comment]
@tanmuhittin please tag a new release, we're all waiting

**Comment by tanmuhittin** [comment]
I am on vacation. Please confirm that new release works. Sorry for the delay. Best regards :)

**Comment by robsonrk** [comment]
Tagged. [#28](https://github.com/tanmuhittin/laravel-google-translate/pull/28)

**Comment by LazyTechwork** [comment]
> I am on vacation. Please confirm that new release works. Sorry for the delay. Best regards :)

New release works, thank you so much)
