### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by DanielMalmgren** [tanmuhittin/laravel-google-translate#35]
When trying to translate files lately I get the following error:

```
In GoogleTranslate.php line 311:

  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl
  .haxx.se/libcurl/c/libcurl-errors.html)

```

Any idea what the problem might be?

**Comment by tanmuhittin** [comment]
Please check https://github.com/tanmuhittin/laravel-google-translate#ssl-certificate-problem-unable-to-get-local-issuer-certificate
