### ISSUE TITLE
No translations returned

### ISSUE THREAD

**Issue by Thedonsolo** [tanmuhittin/laravel-google-translate#48]
The first time I ran the command it returned me some translations but the 2nd run it didn't return anything anymore.
No errors...
Output:
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
en -> nl translating...
/var/www/testproject/resources/lang/nl/admin.php is preparing
Source text collected
Home : 
Online : 
List : 
International : 
Translations : 
Locations : 
Backups : 
My account : 
language : 
languages :

**Comment by Solotov** [comment]
is apparently not using the google translate service and the documentation does not say anything about it!

**Comment by vahidalvandi** [comment]
how i can create custom_api_translator

**Comment by tanmuhittin** [comment]
@vahidalvandi https://github.com/tanmuhittin/laravel-google-translate#how-to-use-your-own-translation-api

**Comment by tanmuhittin** [comment]
@Thedonsolo probably you dont have an api key. in this case stichoza/google-translate-php translator is used. In case an error occurs(you reach some sort of limit) it does not throw any exceptions -> https://github.com/tanmuhittin/laravel-google-translate/blob/master/src/Api/StichozaApiTranslate.php

Maybe it should. I might update this behaviour
