### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by djoudi** [tanmuhittin/laravel-google-translate#50]
λ composer require tanmuhittin/laravel-google-translate
Using version ^2.0 for tanmuhittin/laravel-google-translate
./composer.json has been updated
Running composer update tanmuhittin/laravel-google-translate
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tanmuhittin/laravel-google-translate[2.0.3, ..., 2.0.4] require google/cloud-translate ^1.7.4 -> satisfiable by google/cloud-translate[v1.7.4, ..., v1.12.3].
    - google/cloud-translate[v1.7.4, ..., v1.12.3] require google/gax ^1.1 -> satisfiable by google/gax[1.1.0, ..., v1.11.4].
    - google/gax[v1.9.0, ..., v1.11.4] require google/auth ^1.18.0 -> satisfiable by google/auth[v1.18.0].
    - tanmuhittin/laravel-google-translate[2.0.0, ..., 2.0.2] require illuminate/support ^5.5|^6|^7 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - google/auth v1.18.0 requires psr/cache ^1.0|^2.0 -> found psr/cache[1.0.0, 1.0.1, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - google/gax[1.1.0, ..., v1.8.0] require guzzlehttp/psr7 ^1.2 -> found guzzlehttp/psr7[1.2.0, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires tanmuhittin/laravel-google-translate ^2.0 -> satisfiable by tanmuhittin/laravel-google-translate[2.0.0, ..., 2.0.4].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require tanmuhittin/laravel-google-translate:*" to figure out if any version is installable, or "composer require tanmuhittin/laravel-google-translate:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by tanmuhittin** [comment]
Laravel 9 support recenly added. tag 2.1.0
