### ISSUE TITLE
Respect casing

### ISSUE THREAD

**Issue by DanielMalmgren** [tanmuhittin/laravel-google-translate#6]
I have many one word strings with starts with a capital letter, such as "Name", "Position" etc. After being translated they ended up being completely lower case. Is there any way of respecting the casing of the input string and making the output string similarly cased?

**Comment by tanmuhittin** [comment]
Have you tried translating the same string using Google Translate itself. Looks like the translation service itself is not respecting cases at all.


Example:

https://translate.google.com/#view=home&op=translate&sl=en&tl=sv&text=Please%20write%20your%20Position
